---
Name: deferedimages
---
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - DFT\SilverStripe\DeferedImages\DeferedImage
SilverStripe\Assets\Image:
  extensions:
    - DFT\SilverStripe\DeferedImages\DeferedImage

# Automatically add to pages
---
Only:
  moduleexists: 'silverstripe/cms'
---
PageController:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension

# If searchable installed, auto-add
---
Only:
  moduleexists: 'dft/silverstripe-searchable'
---
DFT\SilverStripe\Searchable\Control\SearchResults:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension

# If users module installed, auto-add
---
Only:
  moduleexists: 'DFT/silverstripe-users'
---
DFT\SilverStripe\Users\Control\RegisterController:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension
DFT\SilverStripe\Users\Control\AccountController:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension
  
# If catalogue frontend installed, add to the controller
---
Only:
  moduleexists: 'silvercommerce/catalogue-frontend'
---
SilverCommerce\CatalogueFrontend\Control\CatalogueController:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension

# If shopping cart installed, add to the controller
---
Only:
  moduleexists: 'silvercommerce/shoppingcart'
---
SilverCommerce\ShoppingCart\Control\ShoppingCart:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension

# If checkout installed, add to the controller
---
Only:
  moduleexists: 'silvercommerce/checkout'
---
SilverCommerce\Checkout\Control\Checkout:
  extensions:
    - DFT\SilverStripe\DeferedImages\ControllerExtension